### PR TITLE
Change Command Name and fix Typo

### PR DESCRIPTION
**Pull request by syntafin**
Changed the Command from ``presenter:make`` to ``make:presenter`` to follow the other commands in Laravel to create new classes.
Fixed small typo in description.

### CODE REVIEW

**Comment by ousid** [comment]
Hey, @syntafin 

Sorry for the late response.

It seems a bit of time since this `PR`.

Changing the command Name could be a breaking changes, and I don't think we could afford that.

What to do instead is, make a new command as an alias, and let the users knows (on the README.md) that there's a main command and an alias.

Looking for your collaborations.

Thanks for your time/PR.

**Comment by syntafin** [comment]
I can take a look into this tomorrow, and commit a alias command.

**Comment by ousid** [comment]
Sounds Great! Thanks, @syntafin

**Comment by syntafin** [comment]
There is now the alias command for it.
I marked ``presenter:make`` as deprecated, so it can be dropped in a future major release.

**Comment by ousid** [comment]
I don't think adding a new alias for a command, needs to deprecate the other one, for example look at livewire commands

`php artisan livewire:mv ...` is an alias for `php artisan livewire:move`

`php artisan make:livewire ...` is an alias for `php artisan livewire:make`

And so on...

Also, I have updated the service provide, and I added an extra test for the new command

**Comment by ousid** [comment]
It looks all the tests passed, thank you, @syntafin, for your PR and your time.

**Pull request merged**
